allow/enforce condition shortcuts for strings and numbers as well
gtap-dev/javascript pull request #15
Opened 2021-07-19 12:17 UTC by mjomble

Fixes #11 

Not sure about enforcing shortcuts for number comparisons.
It makes sense to omit `> 0` in length checks, but more clarity might be good in more math-heavy code.
I added an exception for possibly negative numbers, but perhaps we should just allow deciding this case by case.

2021-11-05 09:14 UTC, mihkeleidast commented on README.md
> +    // good, but keep in mind that an empty array is also truthy in JavaScript (unlike in PHP, for example)
i would label this as bad, because it will allow code to execute that shouldn't

2024-05-09 14:12 UTC, atticushome requested changes

2024-05-09 14:12 UTC, atticushome commented on README.md
> +    // good, but keep in mind that an empty array is also truthy in JavaScript (unlike in PHP, for example)
I would also label this as bad

2024-10-14 15:10 UTC, atticushome approved these changes

2024-10-28 10:43 UTC, Vladislav-Stafinjak approved these changes

2024-10-28 10:43 UTC, merged